### ISSUE TITLE
Fails to start when icon path not valid

### ISSUE THREAD

**Issue by sebastianst** [gerasev-kirill/light-desktop-item-edit#2]
Hi,
I have the most recent version of light-desktop-item-edit installed. Thanks for this helpful app!

When I run the application on a .desktop file whose `Icon=` property does not point to a valid icon file, the app fails to start instead of just printing a warning message which says that the icon file is not available/valid. The following error occurs:
```
/usr/lib/python2.7/site-packages/ldie/desktop_edit.py:37: Warning: The property GtkButton:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.tree.add_from_file(os.path.join(self.file_path, 'desktop-item-edit.ui'))
/usr/lib/python2.7/site-packages/ldie/desktop_edit.py:37: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.tree.add_from_file(os.path.join(self.file_path, 'desktop-item-edit.ui'))
/usr/lib/python2.7/site-packages/ldie/desktop_edit.py:37: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.tree.add_from_file(os.path.join(self.file_path, 'desktop-item-edit.ui'))
Traceback (most recent call last):
  File "/usr/bin/light-desktop-item-edit", line 57, in <module>
    app=ldie.DesktopMainWindow(DATA_PATH, argv[0],"light-desktop-item-edit")
  File "/usr/lib/python2.7/site-packages/ldie/desktop_edit.py", line 63, in __init__
    self.load_desktop_file()
  File "/usr/lib/python2.7/site-packages/ldie/desktop_edit.py", line 193, in load_desktop_file
    self.load_icon()
  File "/usr/lib/python2.7/site-packages/ldie/desktop_edit.py", line 162, in load_icon
    if pixbuf.get_width()>100:
AttributeError: 'NoneType' object has no attribute 'get_width'
```

**Comment by gerasev-kirill** [comment]
761d1cd4a3388d244a0c54736a12860178a11cdd

check it. i don't have arch so i can't even build app.

**Comment by sebastianst** [comment]
Great, this works. Thanks!
